In [1]:
import os
os.getcwd()

'C:\\Users\\simpa\\OneDrive\\Desktop\\fake-news-project-main\\notebooks'

os.listdir("..")

os.listdir("../data")

In [2]:
df = pd.read_csv("data/news.csv")

NameError: name 'pd' is not defined

In [3]:
df = pd.read_csv("./data/news.csv")

NameError: name 'pd' is not defined

In [4]:
df = pd.read_csv("../data/news.csv")

NameError: name 'pd' is not defined

In [5]:
df = pd.read_csv("/data/news.csv")

NameError: name 'pd' is not defined

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("../data/news.csv")
df.head()

,id,title,url,publisher,category,story,hostname,timestamp
0,2,Fed's Charles Plosser sees high bar for change...,http://www.livemint.com/Politics/H2EvwJSK2VE6O...,Livemint,b,ddUyU0VZz0BRneMioxUPQVP6sIxvM,www.livemint.com,1394470371207
1,3,US open: Stocks fall after Fed official hints ...,http://www.ifamagazine.com/news/us-open-stocks...,IFA Magazine,b,ddUyU0VZz0BRneMioxUPQVP6sIxvM,www.ifamagazine.com,1394470371550
2,4,"Fed risks falling 'behind the curve', Charles ...",http://www.ifamagazine.com/news/fed-risks-fall...,IFA Magazine,b,ddUyU0VZz0BRneMioxUPQVP6sIxvM,www.ifamagazine.com,1394470371793
3,5,Fed's Plosser: Nasty Weather Has Curbed Job Gr...,http://www.moneynews.com/Economy/federal-reser...,Moneynews,b,ddUyU0VZz0BRneMioxUPQVP6sIxvM,www.moneynews.com,1394470372027
4,6,Plosser: Fed May Have to Accelerate Tapering Pace,http://www.nasdaq.com/article/plosser-fed-may-...,NASDAQ,b,ddUyU0VZz0BRneMioxUPQVP6sIxvM,www.nasdaq.com,1394470372212

In [8]:
import pandas as pd

In [9]:
os.listdir("../data")

['.gitkeep', '.ipynb_checkpoints', 'news.csv', 'notebooks']

In [10]:
df = pd.read_csv("../data/news.csv")

In [11]:
df.head()

,id,title,url,publisher,category,story,hostname,timestamp
0,2,Fed's Charles Plosser sees high bar for change...,http://www.livemint.com/Politics/H2EvwJSK2VE6O...,Livemint,b,ddUyU0VZz0BRneMioxUPQVP6sIxvM,www.livemint.com,1394470371207
1,3,US open: Stocks fall after Fed official hints ...,http://www.ifamagazine.com/news/us-open-stocks...,IFA Magazine,b,ddUyU0VZz0BRneMioxUPQVP6sIxvM,www.ifamagazine.com,1394470371550
2,4,"Fed risks falling 'behind the curve', Charles ...",http://www.ifamagazine.com/news/fed-risks-fall...,IFA Magazine,b,ddUyU0VZz0BRneMioxUPQVP6sIxvM,www.ifamagazine.com,1394470371793
3,5,Fed's Plosser: Nasty Weather Has Curbed Job Gr...,http://www.moneynews.com/Economy/federal-reser...,Moneynews,b,ddUyU0VZz0BRneMioxUPQVP6sIxvM,www.moneynews.com,1394470372027
4,6,Plosser: Fed May Have to Accelerate Tapering Pace,http://www.nasdaq.com/article/plosser-fed-may-...,NASDAQ,b,ddUyU0VZz0BRneMioxUPQVP6sIxvM,www.nasdaq.com,1394470372212

In [12]:
df.shape

(100, 8)

In [13]:
df.columns

Index(['id', 'title', 'url', 'publisher', 'category', 'story', 'hostname',
       'timestamp'],
      dtype='object')

In [18]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^a-z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean_title"] = df["title"].apply(clean_text)
df[["title", "clean_title"]].head()

,title,clean_title
0,Fed's Charles Plosser sees high bar for change...,feds charles plosser sees high bar for change ...
1,US open: Stocks fall after Fed official hints ...,us open stocks fall after fed official hints a...
2,"Fed risks falling 'behind the curve', Charles ...",fed risks falling behind the curve charles plo...
3,Fed's Plosser: Nasty Weather Has Curbed Job Gr...,feds plosser nasty weather has curbed job growth
4,Plosser: Fed May Have to Accelerate Tapering Pace,plosser fed may have to accelerate tapering pace

In [19]:
trusted_sources = [
    "bbc", "reuters", "theguardian", "nytimes", "cnn","economictimes.indiatimes"
]

def label_from_hostname(hostname):
    hostname = str(hostname).lower()
    for src in trusted_sources:
        if src in hostname:   # partial match
            return 0          # Real (trusted)
    return 1                  # Fake / less credible

df["label"] = df["hostname"].apply(label_from_hostname)

df[["hostname", "label"]].value_counts().head(10)

hostname                      label
in.reuters.com                0        8
www.marketwatch.com           1        4
economictimes.indiatimes.com  0        4
www.ifamagazine.com           1        4
www.globalpost.com            1        4
www.businessinsider.in        1        3
www.reuters.com               0        3
www.businessweek.com          1        3
www.theglobeandmail.com       1        2
www.fxstreet.com              1        2
Name: count, dtype: int64